[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
loglevel=info

[program:kibana]
command=/opt/kibana/bin/kibana
directory=/opt/kibana
autostart=true
autorestart=true
stdout_logfile=/var/log/kibana.stdout.log
stderr_logfile=/var/log/kibana.stderr.log
priority=10

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/var/log/nginx.stdout.log
stderr_logfile=/var/log/nginx.stderr.log
priority=20
